# Generated by Django 5.2.17 on 2026-09-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_preferences_options_alter_preferences_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferences',
            name='budget_max',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='preferred_location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='preferences',
            name='study_habits',
            field=models.CharField(blank=True, default='Flexible', max_length=50),
        ),
    ]
