# Generated by Django 5.2.17 on 2026-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_studentprofile_verification_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomlisting',
            name='rooms_available',
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='amenities',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='current_occupants',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='gender_preference',
            field=models.CharField(choices=[('any', 'Any'), ('male', 'Male'), ('female', 'Female')], default='any', max_length=10),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='move_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='property_type',
            field=models.CharField(choices=[('bedsitter', 'Bedsitter'), ('one_bedroom', '1 Bedroom'), ('two_bedroom', '2 Bedroom'), ('three_bedroom', '3 Bedroom'), ('shared_room', 'Shared Room'), ('other', 'Other')], default='bedsitter', max_length=20),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='spaces_available',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='roomlisting',
            name='utilities_included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roomlisting',
            name='rent_per_person',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
